### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by magicsunday** [bmhm/webtrees-missingtombstones#4]
Leider kann man nicht die GIT-Repo clonen und danach direkt das Modul verwenden, da sich die Verzeichnisstruktur nicht mit der von Webtrees deckt. Damit kann man dann auch nicht auf die jeweils aktuelle Version per `git pull` aktualisieren.

**Comment by bmhm** [comment]
Doch, das geht. Einfach den unterordner `src` auschecken (sparse checkout).

Alternativ wäre noch das "latest" release (als .zip oder .tar.gz)  möglich (/releases/latest).

Dritte Möglichkeit: Das im anderen Issue angesprochene Compile-Repo. 

Generell zum Thema Verzeichnisstruktur:
Ich möchte einfach die test-Sourcen nicht im Hauptcode unterbringen, daher ist ein Verschieben des Codes auf die Hauptebene für mich keine Lösung. Außerdem wird sich mit dem nächsten Webtrees-Release die Modulstruktur sowieso ändern, daher sehe ich auch keinen großen Anlass.

Vielleicht können wir auf lange Sicht ein Modul-Marketplace (ähnlich wie bei Wordpress) erstellen. Webtrees braucht aber ganz dringend Entwickler!

**Comment by magicsunday** [comment]
Naja zumindest die module.php sollte mMn im Root liegen, dass man das Modul "Out of the Box" verwenden kann. Der Rest kann ja weiterhin im src/ und test/ bleiben. `git sparse checkout` finde ich auch keine sonderlich schöne Lösung.

Wo hast du die Info her, dass sich die Modulstruktur ändern wird?

**Comment by bmhm** [comment]
> Wo hast du die Info her, dass sich die Modulstruktur ändern wird?

Direkt vom Entwickler Greg, der /dev-Branch ist schon weiter auf Laravel umgestellt. Es liegt längerfristig einfach auf der Hand.


> Naja zumindest die module.php sollte mMn im Root liegen.

Sehe ich wie gesagt nicht so, da sind die Webtrees-Module eher die Ausnahme:

* http://stackoverflow.com/a/5469035/1549977
* http://stackoverflow.com/a/65814/1549977
* http://www.php-fig.org/psr/psr-4/examples/
* https://book.cakephp.org/3.0/en/intro/cakephp-folder-structure.html
* https://phpunit.de/manual/current/en/organizing-tests.html
usw…

Ich bin aber gewillt, gerne nach einer anderen Lösung Ausschau zu halten.

**Comment by bmhm** [comment]
Hi,

ich hab nochmal nachgedacht. Ich versuche doch die Sourcen wieder ins Root-Verzeichnis zu ziehen 👍 
Das Makefile kann dann ja auch das test-Verzeichnis vom build ausschließen. Das geht schon irgendwie.
